services:
  - type: web
    name: situp-bird-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: situp-bird-server
          property: port
    healthCheckPath: /health